# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # RTD defaults to a depth of 50 but qbittorrent-api versioning may require
      # much more Git history to accurately determine the SCM version
      - git fetch --unshallow
    create_environment:
      # install uv and create the environment RTD builds the docs in
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv --python "3.12" "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --group docs --group dev
    pre_build:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv run tox -e docs-lint

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
