import abc
from collections import Mapping
from collections import MutableMapping

def merge(left, right): ...

class Attr(Mapping, metaclass=abc.ABCMeta):
    def __call__(self, key): ...
    def __getattr__(self, key): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...

class MutableAttr(Attr, MutableMapping, metaclass=abc.ABCMeta):
    def __setattr__(self, key, value) -> None: ...
    def __delattr__(self, key, force: bool = ...) -> None: ...

class AttrDict(dict, MutableAttr):
    def __init__(self, *args, **kwargs) -> None: ...
