from typing import MutableMapping
from typing import Text

from qbittorrentapi.app import AppAPIMixIn
from qbittorrentapi.definitions import ClientCache
from qbittorrentapi.definitions import Dictionary

class RSSitemsDictionary(Dictionary): ...
class RSSRulesDictionary(Dictionary): ...

class RSS(ClientCache):
    items: _Items
    def __init__(self, client: RSSAPIMixIn) -> None: ...
    def add_folder(self, folder_path: Text = None, **kwargs): ...
    addFolder = add_folder
    def add_feed(self, url: Text = None, item_path: Text = None, **kwargs): ...
    addFeed = add_feed
    def remove_item(self, item_path: Text = None, **kwargs): ...
    removeItem = remove_item
    def move_item(
        self, orig_item_path: Text = None, new_item_path: Text = None, **kwargs
    ): ...
    moveItem = move_item
    def refresh_item(self, item_path: Text = None): ...
    refreshItem = refresh_item
    def mark_as_read(
        self, item_path: Text = None, article_id: Text | int = None, **kwargs
    ): ...
    markAsRead = mark_as_read
    def set_rule(
        self, rule_name: Text = None, rule_def: MutableMapping = None, **kwargs
    ): ...
    setRule = set_rule
    def rename_rule(
        self, orig_rule_name: Text = None, new_rule_name: Text = None, **kwargs
    ): ...
    renameRule = rename_rule
    def remove_rule(self, rule_name: Text = None, **kwargs): ...
    removeRule = remove_rule
    @property
    def rules(self) -> RSSRulesDictionary: ...
    def matching_articles(self, rule_name: Text = None, **kwargs): ...
    matchingArticles = matching_articles

    class _Items(ClientCache):
        def __call__(
            self, include_feed_data: bool = None, **kwargs
        ) -> RSSitemsDictionary: ...
        @property
        def without_data(self) -> RSSitemsDictionary: ...
        @property
        def with_data(self) -> RSSitemsDictionary: ...

class RSSAPIMixIn(AppAPIMixIn):
    @property
    def rss(self) -> RSS: ...
    def rss_add_folder(self, folder_path: Text = None, **kwargs) -> None: ...
    rss_addFolder = rss_add_folder
    def rss_add_feed(
        self, url: Text = None, item_path: Text = None, **kwargs
    ) -> None: ...
    rss_addFeed = rss_add_feed
    def rss_remove_item(self, item_path: Text = None, **kwargs) -> None: ...
    rss_removeItem = rss_remove_item
    def rss_move_item(
        self, orig_item_path: Text = None, new_item_path: Text = None, **kwargs
    ) -> None: ...
    def rss_items(
        self, include_feed_data: bool = None, **kwargs
    ) -> RSSitemsDictionary: ...
    def rss_refresh_item(self, item_path: Text = None, **kwargs) -> None: ...
    rss_refreshItem = rss_refresh_item
    def rss_mark_as_read(
        self, item_path: Text = None, article_id: Text | int = None, **kwargs
    ) -> None: ...
    rss_markAsRead = rss_mark_as_read
    def rss_set_rule(
        self, rule_name: Text = None, rule_def: MutableMapping = None, **kwargs
    ) -> None: ...
    rss_setRule = rss_set_rule
    def rss_rename_rule(
        self, orig_rule_name: Text = None, new_rule_name: Text = None, **kwargs
    ) -> None: ...
    rss_renameRule = rss_rename_rule
    def rss_remove_rule(self, rule_name: Text = None, **kwargs) -> None: ...
    rss_removeRule = rss_remove_rule
    def rss_rules(self, **kwargs) -> RSSRulesDictionary: ...
    def rss_matching_articles(
        self, rule_name: Text = None, **kwargs
    ) -> RSSitemsDictionary: ...
    rss_matchingArticles = rss_matching_articles
